# Generated by Django 4.2.4 on 2023-09-26 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_role_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='listens_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tracks_count',
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.listener', verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
    ]
