# Generated by Django 4.2.4 on 2023-10-01 15:32

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_follower_follow_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'исполнитель', 'verbose_name_plural': 'исполнители'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='listener',
            options={'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='firstname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lastname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=64, verbose_name='сценическое имя'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.artist', verbose_name='исполнитель'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата подписки'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.listener', verbose_name='подписчик'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Другое'), ('N', 'Не хочу отвечать')], default='N', max_length=1, verbose_name='гендер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receive_promotions',
            field=models.BooleanField(default=False, verbose_name='получать рекламу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='имя пользователя'),
        ),
    ]
