# Generated by Django 4.2.4 on 2023-09-26 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_artist_albums_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(editable=False, verbose_name='Длительность')),
                ('release', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата релиза')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Коллаборация',
                'verbose_name_plural': 'Коллаборации',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(editable=False, verbose_name='Длительность')),
                ('plays', models.PositiveIntegerField(editable=False, verbose_name='Прослушивания')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='users.artist', verbose_name='Исполнитель')),
                ('collaborators', models.ManyToManyField(through='music.Collaboration', to='users.artist', verbose_name='Коллаборация')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='TrackInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Альбом')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Трек в альбоме',
                'verbose_name_plural': 'Треки в альбомах',
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата релиза')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Сингл',
                'verbose_name_plural': 'Синглы',
            },
        ),
        migrations.AddField(
            model_name='collaboration',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='Трек'),
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('track', 'artist')},
        ),
    ]
