# Generated by Django 4.2.6 on 2023-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_duration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackinalbum',
            table='track_in_album',
        ),
    ]
